#!/usr/bin/with-contenv bash

if [ "${PROXY_ENABLED}" != "true" ]; then
    s6-svc -d .
    exit 0
fi

command="pproxy -l http://0.0.0.0:${PROXY_PORT}"
if [[ -n ${PROXY_USER:-} ]] && [[ -n ${PROXY_PASS:-} ]]; then
    command="$command#${PROXY_USER}:${PROXY_PASS}"
fi
command="$command --auth ${PROXY_AUTHTIME:-0}${PROXY_VERBOSE+ -v}"

echo "*** executing => $command"
# exec s6-setuidgid abc $command
exec s6-setuidgid abc $command | \
   grep -E -v --line-buffered "^http 127\.0\.0\.1\:[[:digit:]]{5} -> ?google\.com\:443$" | \
   ts '[%Y/%m/%d %H:%M:%S]'
