#!/usr/bin/with-contenv bash

WGCF_ACCOUNT="/config/wgcf-account.toml"
WGCF_PROFILE="/config/wgcf-profile.conf"

_wgcf() { wgcf --config "$WGCF_ACCOUNT" "$@"; }

if [ ! -e "$WGCF_ACCOUNT" ]; then
  echo "*** wgcf: Registering a new account..."
  _wgcf register --accept-tos${WGCF_DEVICE_NAME+ -n "$WGCF_DEVICE_NAME"}
fi

echo "*** wgcf: Updating account info..."
_wgcf update${WGCF_DEVICE_NAME+ -n "$WGCF_DEVICE_NAME"}

private_key=$(awk '/^private_key/{print $3}' "$WGCF_ACCOUNT")
if [ ! -e "$WGCF_PROFILE" ]; then
  echo "*** wgcf: Generating a new wireguard profile..."
  _wgcf generate --profile "$WGCF_PROFILE"
elif [ "${private_key//\'/}" != "$(awk '/^PrivateKey/{print $3}' "$WGCF_PROFILE")" ]; then
  echo "*** wgcf: Updating wireguard profile..."
  rm -f "$WGCF_PROFILE"
  _wgcf generate --profile "$WGCF_PROFILE"
fi

if [ ! -e "/config/wireproxy.conf" ]; then
  {
    echo "WGConfig = $WGCF_PROFILE"
    echo -e "[Socks5]\nBindAddress = 127.0.0.1:8080"
  } > "/config/wireproxy.conf"
fi

# permissions
chown -R abc:abc \
  /config
