#!/usr/bin/with-contenv bash

if [ "${WARP_ENABLED}" != "true" ] || [ "${WARP_PLUS}" != "true" ]; then
    s6-svc -d .
    exit 0
fi

command="warp-plus${WARP_PLUS_VERBOSE+ -v} run"

echo "*** executing => $command"
exec s6-setuidgid abc $command
