#!/usr/bin/with-contenv bash

if [ "${WARP_PLUS}" != "true" ] || [ "${WARP_ENABLED}" != "true" ]; then
    exit 0
fi

s6-svwait -u /run/service/wireproxy

until [ "$(curl --retry 10 --retry-connrefused --retry-delay 5 -ks https://www.cloudflare.com/cdn-cgi/trace -x socks5://127.0.0.1:8080 | grep warp | sed 's/warp=//g')" == "plus" ] ; do
    warp-plus -v update
    echo "Wait 10s for WARP+ ready..."
    sleep 10
    s6-svc -r /run/service/wireproxy && sleep 1
    s6-svwait -u /run/service/wireproxy
done

echo "*** WARP Mode: $(curl -ks https://www.cloudflare.com/cdn-cgi/trace -x socks5://127.0.0.1:8080 | grep warp | sed 's/warp=//g') ***"
echo "*** WARP is running! ***"