#!/command/with-contenv bash
cd /wgcf

if [ "${WARP_ENABLED}" = "true" ]; then
  if [ ! -e "/wgcf/wgcf-account.toml" ]; then
    wgcf register --accept-tos
    chown abc:abc wgcf-account.toml
  fi

  wgcf generate
  chown abc:abc wgcf-profile.conf

  cp /wgcf/wgcf-profile.conf /etc/wireguard/wgcf.conf
  DEFAULT_GATEWAY_NETWORK_CARD_NAME=`route  | grep default  | awk '{print $8}' | head -1`
  DEFAULT_ROUTE_IP=`ifconfig $DEFAULT_GATEWAY_NETWORK_CARD_NAME | grep "inet " | awk '{print $2}' | sed "s/addr://"`

  sed -i "/\[Interface\]/a PostDown = ip rule delete from $DEFAULT_ROUTE_IP  lookup main" /etc/wireguard/wgcf.conf
  sed -i "/\[Interface\]/a PostUp = ip rule add from $DEFAULT_ROUTE_IP lookup main" /etc/wireguard/wgcf.conf

  if [ "${SYNOLOGY}" = "true" ]; then
    # for synology
    sed -i 's/AllowedIPs = ::/#AllowedIPs = ::/' /etc/wireguard/wgcf.conf
    sed -i 's/AllowedIPs = 0.0.0.0\/0/AllowedIPs = 0.0.0.0\/1, 128.0.0.0\/1/' /etc/wireguard/wgcf.conf
  else
    modprobe ip6table_raw
  fi
  echo "*** wgcf ready! ***"
fi