#!/command/with-contenv bash

if [ "${WARP_ENABLED}" = "true" ]; then
    
    wg-quick up wgcf &>-
    
    while ! curl -s -o /dev/null --max-time 2 ipinfo.io ; do
        wg-quick down wgcf
        echo "Sleep 2 and retry again."
        sleep 2
        wg-quick up wgcf
    done

    if [ "${WARP_PLUS}" = "true" ]; then
        while [ "$(curl -ks https://www.cloudflare.com/cdn-cgi/trace | grep warp | sed 's/warp=//g')" != "plus" ] ; do
            echo "Wait for WARP+ ready..."
            sleep 10
            python3 /etc/s6-overlay/scripts/warp_plus.py -v update
            wg-quick down wgcf &>-
            sleep 2
            wg-quick up wgcf &>-
            while ! curl -s -o /dev/null --max-time 2 ipinfo.io ; do
                wg-quick down wgcf
                echo "Sleep 2 and retry again."
                sleep 2
                wg-quick up wgcf
            done
        done
    fi

    echo "*** Warp Mode: $(curl -ks https://www.cloudflare.com/cdn-cgi/trace | grep warp | sed 's/warp=//g') ***"
    echo "*** warp is running! ***"
fi