#!/usr/bin/with-contenv bash

if [ "${PROXY_ENABLED}" != "true" ]; then
    s6-svc -d .
    exit 0
fi

s6-svwait -u /run/service/svc-wireproxy && sleep 1s

command="pproxy -l http://0.0.0.0:${PROXY_PORT}"
if [[ -n ${PROXY_USER:-} ]] && [[ -n ${PROXY_PASS:-} ]]; then
    command="$command#${PROXY_USER}:${PROXY_PASS}"
fi
command="$command -r socks5://127.0.0.1:8080"
command="$command --auth ${PROXY_AUTHTIME:-0}${PROXY_VERBOSE+ -v}"

echo "*** executing => $command"

exec s6-setuidgid abc $command | \
    sed -u 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' | \
    grep -E -v --line-buffered "http 127\.0\.0\.1:[[:digit:]]{5} -> (socks5 127\.0\.0\.1:8080 -> )?google\.com:443$"
