#!/usr/bin/with-contenv bash

if [ "${WARP_ENABLED}" != "true" ]; then
    s6-svc -d .
    exit 0
fi

command="wireproxy -c /config/wireproxy.conf"

echo "*** executing => $command"
# exec s6-setuidgid abc $command

exec s6-setuidgid abc $command | \
   grep -E -v --line-buffered "^DEBUG:" | \
   sed -u 's/^/[WIREPROXY] /' | \
   ts '[%Y/%m/%d %H:%M:%S]'